config:
  server:
    port: 8080
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: harbor06.chint.com/chint-public/demo/bookstore
  tag: dev
nameOverride: ""
replicas: 1
resources: {}
rbac:
  create: true
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  hosts:
    - host: bookstore.chintcloud.net
      serviceName: bookstore
      servicePort: 8080
jmx:
  enabled: true
  name: jmx
  port: 5556
  image:
    pullPolicy: Always
    repository: harbor06.chint.com/chint-public/bitnami/jmx-exporter
    tag: 0.12.0

