config:
  server:
    port: 8080
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: stonewlg/bookstore
  tag: latest
nameOverride: ""
replicas: 1
resources: {}
rbac:
  create: true
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  hosts:
    - host: bookstore.dev.chintcloud.net
      serviceName: bookstore
      servicePort: 8080
jmx:
  enabled: false
  name: jmx
  port: 5556
  image:
    pullPolicy: Always
    repository: bitnami/jmx-exporter
    tag: 0.12.0

skywalking:
  enabled: true
  service_name: bookstore
  backend_service: "skywalking-skywalking-oap.skywalking.svc.cluster.local:11800"
