{{- if .Values.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}  
data:
  application.yaml: |-
    server:
      port: {{ .Values.config.server.port }}
  jmx.yaml: |-
    hostPort: "localhost:7190"
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true    
{{- end }}
