{{- if .Values.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}  
data:
  application.yaml: |-
    server:
      port: {{ .Values.config.server.port }}
{{- end }}
