apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config }}
          volumeMounts:
            - name: config
              subPath: application.yaml
              mountPath: /application.yaml
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.jmx.enabled }}
        - name: {{ .Values.jmx.name }}
          image: "{{ .Values.jmx.image.repository }}:{{ .Values.jmx.image.tag }}"
          imagePullPolicy: {{ .Values.jmx.image.pullPolicy }}
          args:
          - "{{ .Values.jmx.port }}"
          - "/jmx.yaml"            
          {{- if .Values.config }}
          volumeMounts:
            - name: config
              subPath: jmx.yaml
              mountPath: /jmx.yaml
          {{- end }}                   
        {{- end }}
      {{- if .Values.config }}     
      volumes:
        - name: config
          configMap:
            name: {{ include "application.fullname" . }}
      {{- end }}
