{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "application.labels" . | nindent 4 }}
{{- end -}}
